apiVersion : apps/v1
kind: Deployment
metadata:
  name: "darkarmycluster-7dad"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "darkarmycluster-7dad"
  template:
    metadata:
      labels:
        app: "darkarmycluster-7dad"
    spec:
      containers:
        - name: "darkarmycluster-7dad"
          image: "armyclusterregistry.azurecr.io/darkarmycluster"
          ports:
          - containerPort: 80