apiVersion: v1
kind: Service
metadata:
    name: "darkarmycluster-baa1"
    labels:
        app: "darkarmycluster-baa1"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "darkarmycluster-baa1"